### PR TITLE
refixing some things due to duplicated datasets

### PR DESCRIPTION
**Pull request by LinguList**
I see now, how bad an idea it was to just change names in datasets, as we had duplicates now. I fixed them all (I hope), and I also made some final change to names forgotten, including cogdetbench for List2014 datset, baidial for baidialectsurvey/bds, baidialcog for our example of adding only cognates, and I changed the chinese dataset by wang feng to "bcd", as this (Basic words in Chinese Dialects) is the official title, as I now found out.

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList when I run `lexibank cldf baidial` I get python lists for all the segments, i.e. `clean_string` seems to return a list. Do I have to update lingpy?

**Comment by xrotwang** [comment]
Another issue I found: In `baidial` the word IDs are prefixed with `Allen2007-`, whereas in `baidialcogs` the prefix is `cdbs-`. I guess that should be fixed in `baidialcogs.__init__`.

**Comment by xrotwang** [comment]
I also think `baidialcogs` needs to create a CLDF dataset, too, simply because of the accompanying metadata file, which is our link to the cognates. I'll try a fix for these things.

**Comment by LinguList** [comment]
just found the reason for the first, I actually forgot it myself:

```python

>>> clean_string('this')
['th i s']
>>> clean_string('this/that')
['th i s', 'th a t']
```
So we need clean_string(xxx)[0], if we only want to take the first element as a default for the segments.

This is a wanted behaviour, as clean_string ideally also allows us to automatically split the entries and add them in a new row in the data...

**Comment by LinguList** [comment]
the second issue: yes, I think I hard-coded it, since I did not know how to reference the dataset.

**Comment by LinguList** [comment]
I should check to which degree the "cleanstring" was actually really used this way: it is possible, that at some points ' '.join(xxx) is used to resolve, which is, of course, wrong, as it would render words that should be separated in one string.

**Comment by LinguList** [comment]
As to the separate cldf: would this mean that we always create new data, but just adopt some practice for cross-referencing? I'm fine with all solutions, and this might be the safer one, as I suspect that most cases will involve modification of data, not only a re-statement of the relations between the words...

**Comment by xrotwang** [comment]
Creating a CLDF dataset does not necessarily mean copying the data. We only need a `<name>.csv` (potentially with 0 rows) as anchor for `<name>.csv-metadata.json`, because in the latter metadata file, the contents of `cognates.csv` will be described.

**Comment by LinguList** [comment]
just found the following cases, where cleanstring is used:

```text
baidial/__init__.py:                        clean_string(wl[k, 'value']),
grollemundbantu/__init__.py:        return ' '.join(clean_string(string))
kitchensemitic/__init__.py:                    cleaned_string = clean_string(col, merge_vowels=True,
sidwellaustroasiatic/__init__.py:            segments = clean_string(form)
wheelerutoaztecan/__init__.py:                            ' '.join(clean_string(form)),
```

should I check them apart from baidial, or are you going to do that when fixing the bai-case?

**Comment by xrotwang** [comment]
I'll have a look. I think I unfortunately named a function in `lexibank.util` `clean_string`, too.

**Comment by xrotwang** [comment]
@LinguList Just found two weird rows in the baidialcogs raw data: https://github.com/glottobank/lexibank-data/blob/master/datasets/baidialcogs/raw/BDS-cognates.tsv#L308-L309
An artifact?

**Comment by LinguList** [comment]
wanted artefact (but unwanted in this form), as I was too lazy to fill
in all fields. I was doing the cognates yesterday with the edictor. The
zero-field should've been filled by the script I wrote, as the rule is:
same concept, same language has the real id which is needed. The word
ids for these words are:

Lanping: Allen-2007-2785
Jianchuan: Allen2007-2782

**Comment by xrotwang** [comment]
After some more thinking, I guess we should always copy the source data for derived datasets; otherwise the workflow gets too complicated and too many dependencies are introduced. E.g. 
- we'd have to figure out the order in which to generate CLDF from all datasets or
- updates in one dataset may break CLDF creation for another.

So I think, dependencies should only be declared in metadata - and considering source and derived data are available in lexibank CLDF, checking any differences shouldn't be too difficult - we could even think of a `lexibank diff` command.

I'm not quite sure, though, what to do in the lexibank app. We would not want to inflate the number of lexemes artificially. But on the other hand, assuming that most derived datasets change the source data in some ways, there seems to be no clear-cut way to decide which lexeme data to import. I guess, the most transparent thing would just be to live with duplication, in particular because we have all the info to mark derived data.

**Comment by LinguList** [comment]
Allright. Should we leave the Bai case still as an example for inter-data relations, or should we combine it directly? As the data is not published anyway, it was more a toy-example to illustrate this. But I'm also fine to leave it as is.

Another point I was jus thinking about is the following:

With the concepticon_id and the language_variety+glottocode, we could actually count all words in the lists, excluding all unique ones. So in the major statistic on the front page, we would only have this number, not the number of duplicated derived datasets. This would not over-exaggerate the scores, and our claim to be a repository for datasets can easily be maintained.

**Comment by xrotwang** [comment]
But Allen 2007 is given as source of the Bai data, right? So it would seem published somehow.

I have detailed how I think we should handle cases such as this at https://github.com/glottobank/lexibank-data/issues/55#issuecomment-243148027

**Comment by xrotwang** [comment]
Btw. I will fix the two Bai datasets to adhere to the proposed procedure.

**Comment by LinguList** [comment]
Yes, I'd give Allen2007, call it Bai-Dialect Survey (baidial), and have the cognate sets added to it, calling myself "expert".

BTW (sorry for asking many questions): if I create data like the by data, but have no real reference or bibliographical account for this, is there a way to include it as part of LexiBank, or should I fix it via Zenodo myself? Apart from published papers, it may be possible that people would publish things with LexiBank, also as a shortcut. This is similar for @thiagochacon with the Tukano data, on which we (mostly he) worked, but never published.

**Comment by xrotwang** [comment]
I think it should be possible to publish these things via lexibank. The procedure I have in mind is as follows:

Whenever an unpublished dataset is added to `glottobank/lexibank-data`, we create raw data and cldf data, and then make a release of the repository tagged with the name of the dataset. This release will be picked up by ZENODO, so we get a DOI with a bit of a delay. While it may seem a bit confusing that a release called `tukano` would then contain all of lexibank up to that point, it also makes sense, because it may be derived from any of the datasets that came before. Other than somewhat unnecessary file-size of the ZENODO archives, I don't see any drawback of this approach.

**Comment by LinguList** [comment]
But in the lexibank-representation itself, it should be listed as "please quote this source as: Author, Year, Title. DOI." and we don't have the DOI in the moment we create it. What they do in the code-journal on github is actually making repos of an organization, turning them into a doi, and publishing this. Wouldn't that be easier to appear in the workflow? I see the point that it is more fiddling with things, but having a quote like:

Chacon, Thiago (2016): Alignments of the Tukano languages. In: LexiBank. A repository for lexical datasets in historical linguistics and dialectology. Jena: Max Planck Institute for the Science of Human History. DOI: xxxxx

Would be more thrilling, than a doi that is just named after this (and then we had to re-modify the doi in the metadata.json anyway...

**Comment by xrotwang** [comment]
I don't understand "actually making repos of an organization, turning them into a doi, and publishing this"

**Comment by xrotwang** [comment]
Regarding the artefacts: There's seven more of them - just grep "\t0\t". What to do with them?

**Comment by xrotwang** [comment]
Ok, I just read up on JOSS. The actually [are a crossref member which allows them to mint DOIs](http://joss.theoj.org/about#business_model). So there is some cost involved in doing this. We could presumably assign DOIs for free, using [the DOI service of the Max Planck Digital Library], though.

**Comment by LinguList** [comment]
some DOI way will probably be needed, as both ways, the repo-way I suggested (with a github-organization LexiBank, or the one you proposed) will be circular, and make it difficult to cross-refernece things.

As to the problem with \t0\t, I attach the corrected file.

[BDS-cognates.tsv.zip](https://github.com/glottobank/lexibank-data/files/442829/BDS-cognates.tsv.zip)

I forgot to check, the script was actually not working. But now it's fixed.

**Comment by xrotwang** [comment]
ok, will contact MPDL about their DOI service.

**Pull request merged**
