### PR TITLE
More fine-grained transcription reports

### PR DESCRIPTION
**Pull request by LinguList**
command `lexibank report` creates now a file "transcription.md", but requires presence of:

* column "Segments" in the CLDF (otherwise it takes too long and can't be controlled)
* command "report" in __init__.py (don't know why this is now required)

I faced many problems, and I can't solve them right now, so help is appreciated:

* how do I pass a keyword argument to something like the "report" command? Since some data has been explicitly segmentized, we need to take the value in column "Segments", and flag data as "segmentized=true", otherwise it gives wrong results
* can we segmentize ABVD initially? I don't understand, how ABVD works, as the init script differs from the ones we normally have
* how can we add some feedback or debug-functionality? some commands take so long to run, I need some visual feedback that they are not just broken

I think, if we put it like this:

1. lexibank cldf as a command is responsible for segmentation, be it with lingpy, or that it is already in the data
2. lexibank report (or lexibank readme) can then simply as a default only take the column "Segments" for all operations  (especially in dataset.test_sequences), since this makes it a lot easier, and we don't have to fiddle with the arguments.
3. if column "segments" does not exist in the dataset, don't do a report.

Unfortunately, I don't know how to check for point 3, without loading a complete dataset, I don't know how to get back to the default behaviour of lexibank report, that does no longer require that the command is provided in the __init__. I also don't know how to best account for some debugs, or some feedback on progress.

What I added to the transcription report is a list of bad words, a full list of segments, and the function that turns this into a tabular markdown. Compare, for examples:

* the [SEgments](https://github.com/LinguList/lexibank-data/blob/master/datasets/baidial/TRANSCRIPTION.md#segments), and
* the [Words](https://github.com/LinguList/lexibank-data/blob/master/datasets/baidial/TRANSCRIPTION.md#words)

### CODE REVIEW

**Comment by LinguList** [comment]
I just added another display on github, using badges, to make it look nicer with the error-report on words. Only changed kitchensemitic so far:

* https://github.com/LinguList/lexibank-data/blob/master/datasets/kitchensemitic/TRANSCRIPTION.md#words

**Comment by xrotwang** [comment]
Ok. I merge and try to have a look while on the train.

**Comment by xrotwang** [comment]
I think the badge display is a bit heavyweight - not only does it load really slow, it also blows up file sizes. Why not use <s> strikethrough </s> to mark both kinds of error?

**Comment by LinguList** [comment]
I don't really care, I was just experimenting, as my initial test was not really convincing, with bold marking and italics, where you don't see it. I wanted to distinguish two error-kinds, lingpy and clpa, with lingpy being worse, as it means there's really something wrong with the text. 

For me, the report should ideally anyway be written in some expanded JS application, where users can sort, and really test what has gone wrong. So switching to strikethrough is currently a good compromise, I think.

**Pull request merged**
