### PR TITLE
Adding initial functionalities for testing phonetic transcriptions

### PR DESCRIPTION
**Pull request by LinguList**
This PR is preliminary adding functionalities to write phonetic "reports", using a command like:

```sh
$ lexibank report dataset
```
The result is a summary on all phonetic segments in the data, and whether they are recognized or not.

TWo checks are used:

* lingpy compatibility
* clpa compatibility

Detailed reports are produced for each sound segment in the data, and statistics are reported (badges are still missing).

The report functionality makes use of a new lingpy-function, called lingpy.sequence.sound_classes.clean_string, which automatically tries to get the best of potential phonetic information out of an entry, ignoring brackets, splitting entries if they contain commans, etc., also segmentizing (rather smartly). It requires an additional function "report" in the init-file. 

Two other libs were modified for this:

* pyclpa (clpa) with a new function for testing strings
* lingpy with the new cleaning function

PRs for those libs are both pending.

Two datasets are further added, all SEA languages, covering quite a few dialects.

### CODE REVIEW

**Comment by LinguList** [comment]
forgot to mention this: the PR contains additional utility functions which might be good for general purposes (downloading zipfiles) or better put somewhere else, yet I thought I better leave the major structure untouched and leave it to later discussions/modifications to integrate it (or not).

**Comment by LinguList** [comment]
just realized, that the "report" should be probably fill into the readme function. However, I suggest to leave it separated for the moment, as we still don't know how it could be completely integrated (?).

**Comment by xrotwang** [comment]
Did you push clpa and lingpy?

**Comment by LinguList** [comment]
yep, there are two prs pending...

**Comment by xrotwang** [comment]
Ok, I pulled the new functionality, did a bit of refactoring (already pushed) and ran into these problems:
- `lexibank report datasets/wold` results in a lingpy error:
```
  File "datasets/wold/__init__.py", line 52, in report
    test_sequences(ds, 'Value', segmentized=False)
  File "/home/shh.mpg.de/forkel/venvs/lexibank/lexibank-data/pylexibank/lingpy_util.py", line 72, in test_sequences
    row[column], errors=errors, stats=stats, **keywords)
  File "/home/shh.mpg.de/forkel/venvs/lexibank/lexibank-data/pylexibank/lingpy_util.py", line 39, in test_sequence
    segments = clean_string(sequence, **keywords)[0].split(' ')
  File "/home/shh.mpg.de/forkel/venvs/lexibank/lingpy/lingpy/sequence/sound_classes.py", line 1423, in clean_string
    merge_vowels=merge_vowels)
  File "/home/shh.mpg.de/forkel/venvs/lexibank/lingpy/lingpy/sequence/sound_classes.py", line 224, in ipa2tokens
    new_out = [out[0]]
IndexError: list index out of range
```

- running the sequence tests seems to create temporary directories which are not cleaned up:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	7481097-036610e905af4ea7fbc3de01fa443d8b08f4c684/
	lingpy-partial-cognate-detection-2089b49/
```

**Comment by LinguList** [comment]
okay, the latter is something related to the with_temp_dir function which I don't understand, since I thought this would create a temporal dictionary that would directly be deleted

the first error, I just also encountered it, occurs if there is an EMPTY sequence in the Value field of a cldf dataset which is passed to the ipa2tokens function.

I had the same issue in wwua, where the check for missing entries included only "?", not missing values (field.strip(), or whatever). And it makes sense to treat empty value fields as missing entries, I guess, so the test_sequences functions should either check for missing values, or ideally, this should already been done in the cldf-function of each init-file.

**Comment by xrotwang** [comment]
Yes, you are right. The `cldf` function should make sure not to create rows with empty `Value`.

**Comment by xrotwang** [comment]
@LinguList yes, `with_tmp_dir` does remove the tmp dir upon exiting the context, but you extract files to the current working directory and then just copy them somewhere else, instead of moving:
```python
                zipf.extract(path)
                shutil.copy(path, dataset.raw.as_posix())
```

**Comment by LinguList** [comment]
a I see! I'm currently trying to add a function for automatic cognate judgments (in the spirit of the "report" stuff in lingpy_utils), so I'll just take care of this.

**Comment by xrotwang** [comment]
I'm at it, too.

**Comment by LinguList** [comment]
allright, thanks, then I'll leave my fingers from it and test further on the wwua database (I'll make a direct function there which can later easily be transferred to another place).

**Comment by xrotwang** [comment]
alright. Just pushed the small fix.

**Comment by LinguList** [comment]
okay, thanks, then I'll try and add a cognate-detection function and test it on wwua and some other smaller datasets. I figured, if I use the clean_string-function from lingpy on the Value, this should also be written to cldf, but ideally, we would add some notification to the meta-data, indicating that this value has been automatically created (for IDS, it could be combined with unidecode etc.).

**Comment by LinguList** [comment]
cognate detection and the rest now basically works, will push a PR soon, but I needed to fix another lingpy issue (directly pushed it, since tests were OK, and it was rather cosmetical).

**Pull request merged**
